config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
 	resources :users , except: [:new]
 	get 'signup', to: 'users#new'

  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 1, maximum: 35 }
  validates :description, presence: true, length: { minimum: 5, maximum: 200 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
	validates :name , presence: true, uniqueness: true , length: {minimum: 3, maximum: 26}
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	before_save {self.email = email.downcase}
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 5, maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
	#!!curent_user <-- this same
	#this method return true if user logged in
	current_user != nil
end

def require_user
	if !logged_in?
		flash[:danger] = "You must be looged in to perform that action"
		redirect_to root_path
	end
end




end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :find_params, only: [:edit, :show , :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user , only: [:edit , :update, :destroy]


  def index
    @articles = Article.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def edit; end

  def new
    @article = Article.new
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'successful updated articles'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'successfuly created article'
      redirect_to article_path(@article)
    else
      flash[:danger] = "you could't crate a new article "

      # puts @article.errors.inspect
      render 'new'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'sucessful deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def find_params
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can change only your article"
      redirect_to root_path
    end

  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except:[:index, :show]

  def index
  	@categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def home
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		flash[:success] = "successfuly created category"
  		redirect_to categories_path
  	else
  		render 'new'
  	end

  end

  def show
  end


private

def category_params
	params.require(:category).permit(:name)
end
 
 def require_admin
  if !logged_in? || (logged_in? and !current_user.admin?)
    flash[:danger] = "only admins can perform that action"
    redirect_to categories_path

 end


end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  	redirect_to articles_path if logged_in?

  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	 	user = User.find_by(email: params[:session][:email].downcase)
	 	if user && user.authenticate(params[:session][:password])
	 		session[:user_id] = user.id
	 		flash[:success]= "you have successfuly login"
	 		redirect_to user_path(user)
	 		else
	 				flash.now[:danger] = "there was smothing wrong "
	 				render 'new'
					 	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "you have logged out"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

before_action :set_user,  only: [:show, :edit, :update]
before_action :require_same_user , only: [:edit, :update, :destroy]
before_action :require_admin , only: [:destroy]

  def new
    @user = User.new
  end

  def show
    #@user = User.find(params[:id])
    @user_article = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  
  def destroy
    @user = User.find(params[:id])
    @user.destroy 
    flash[:danger] = "successfuly has been daleted accout with us articles"
    redirect_to users_path
  end




  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Successfuly created user'
      redirect_to user_path(@user)
    else
      render 'new'
  end
end

    def edit
      #@user = User.find(params[:id])
    end

    def update
      #@user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Successfuly updated"
        redirect_to articles_path
      else
        render 'edit'
    end
  end
  


    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "Successfuly updated"
        redirect_to articles_path
      else
        render 'edit'
    end
  end
  


  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger]= "You can only edit own accout"
      redirect_to root_path
    end
  end

 def require_admin
  if logged_in? and !current_user.admin?
    flash[:danger] = "only admin can perform that action"
    redirect_to root_path
  end
end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.haml
- obj.each do |article|
  .row
    .col-md-8.offset-2
      .well.well-lg
        .article-title
          =link_to "Title: #{article.title}", article_path(article)
        .article-body
          =truncate("Description: #{article.description}", length: 100)
          %small Created by: #{article.user.name}
          = article.created_at

app/views/articles/_form.html.haml
=render 'shared/errors' , obj: @article
.row
  .col-md-12.offset-2
    =form_for @article do |d|
      .form-group
        .control-label.col-sm-12.formsize
          = d.label :title
        .col-sm-8
          = d.text_field :title, class: "form-control", placeholder: "Your title", autofocus: true
        .form-group
          .control-label.col-sm-12.formsize
            = d.label :description
          .col-sm-8
            = d.text_area :description, class: "form-control", placeholder: "Description for your article", autofocus: true
          .form-group
            .row
              .col-sm-10.offset-2
                = d.collection_check_boxes :category_ids, Category.all, :id, :name do |cd|
                  - cd.label(class: "checkbox-inline input_checkbox") {cd.check_box(class: "checkbox") + cd.text}
        .form-group
          .col-sm-10
            = d.submit class: "btn btn-primary"
      .col-xs-4.col-xs-offset-4
        = link_to "back to articles lisning" , articles_path, class: "btn btn-outline-info btn-md"

app/views/articles/edit.html.haml
%h1 Edit your registration

= render 'articles/form'

app/views/articles/index.html.haml
%h1{align: "center"} Lisning all articles
.center
  =will_paginate
%p
  =render 'article', obj: @articles
.center
  =will_paginate

app/views/articles/new.html.haml
.container
  %h1.articlenew{align: "center"} Creating new article

  = render 'articles/form'

app/views/articles/show.html.haml
%h2{align: "center"} Title:#{@article.title}
.well.col-xs-8.offset-2
  %h4.center
  %strong Description:
  =simple_format(@article.description)
  .userinfo
  %h5 Created at: #{@article.created_at}
  %h5 by: #{@article.user.name}
  .article-actions
    .mysection
      - if logged_in? && (current_user == @article.user || current_user.admin?)
        =link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary"
        =link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "are you sure? "}, class: "btn btn-md btn-danger"
        =link_to "Back to articles listning", articles_path(@article), class: "btn btn-md btn-info"

app/views/categories/home.html.haml
%h1 Categories#home
%p Find me in app/views/categories/home.html.haml

app/views/categories/index.html.haml
%h1{align: "center"} Listning all categories
= will_paginate
- @categories.each do |d|
  %ul.listing
    .row
      .well.col-md-4.offset-4
        %li.article_title
          =link_to "#{d.name}", category_path(d)

app/views/categories/new.html.haml
%h1{align: "center"} Create a new category
=render 'shared/errors' , obj: @category
.row
  .col-md-12.offset-2
    =form_for @category do |d|
      .form-group
        .control-label.col-sm-12.formsize
          = d.label :name
        .col-sm-8
          = d.text_field :name, class: "form-control", placeholder: "Category", autofocus: true
        .form-group
          .col-sm-10
            = d.submit "create" ,class: "btn btn-primary"
      .col-xs-4.col-xs-offset-4
        = link_to "back to articles lisning" , articles_path, class: "btn btn-outline-info btn-md"

app/views/layouts/_flash.html.haml
.container
.row
  .col-xs-10.col-xs-offset-1
    -flash.each do |name,msg |
      .alert{class: "alert-#{name}"}
        =content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %small
      Copyright &copy;
      %a{:href => "https/www.udemy.pl"}
      The complite
    %nav
      %ul
        %li
        =link_to "About", about_path, class: "lefttext"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to "FirstBlog",root_path, class: "navabar-brand", id: "logo"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if logged_in?
      %ul.navbar-nav.mr-auto
        %li.nav-item
          =link_to "Articles", articles_path, class: "nav-link"
        %li.nav-item
          =link_to "Categories", categories_path, class: "nav-link"
        %li.nav-item
          =link_to "Users", users_path, class: "nav-link"
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Setting
            ="admin" if current_user.admin?
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            =link_to "new Article", new_article_path, class: "dropdown-item"
            %a.dropdown-item
              =link_to "My profile", user_path(current_user), class: "dropdown-item"
            .dropdown-divider
            %a.dropdown-item
              =link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item"
        %form.form-inline.my-2.my-lg-0
        %li.nav-item
          =link_to "Logout", logout_path ,method: :delete, class: "nav-link"
    - else
      %form.form-inline.my-2.my-lg-0
        %li.nav-item
          =link_to "Login", login_path, class: "nav-link"
        %li.nav-item
          =link_to "Sign up", signup_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FirstBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/navigation'
    =render 'layouts/flash'
    .container
      = yield
    = render 'layouts/footer'

app/views/pages/home.html.haml
.jumbotron.jumbotron-fluid.center
  .container
    %h1.display-4 First Blog
    =link_to "sign up", signup_path, class: "btn btn-primary btn-lg "
    =link_to "log in", login_path, class: "btn btn-primary btn-lg"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .error_explanation
    .alert.alert-danger
      The from contains
      =pluralize(obj.errors.count, "error")
      %ul
      - obj.errors.full_messages.each do |msg|
        %li
        = msg

app/views/users/_form.html.haml
=render 'shared/errors' , obj: @user
.row
  .col-md-12.offset-2
    =form_for @user do |d|
      .form-group
        .control-label.col-sm-12.formsize
          = d.label :Name
        .col-sm-8
          = d.text_field :name, class: "form-control", placeholder: "Name", autofocus: true
        .form-group
          .control-label.col-sm-12.formsize
            = d.label :Email
          .col-sm-8
            = d.text_field :email, class: "form-control", placeholder: "Email", autofocus: true
        .form-group
          .control-label.col-sm-12.formsize
            = d.label :Password
          .col-sm-8
            = d.password_field :password, class: "form-control", placeholder: "Password", autofocus: true
        .form-group
          .col-sm-10
            = d.submit(@user.new_record? ? "Sing Up" : "Update account" ,class: "btn btn-primary")
      .col-xs-4.col-xs-offset-4
        = link_to "back to articles lisning" , articles_path, class: "btn btn-outline-info btn-md"

app/views/users/edit.html.haml
%h1{align: "center"} Edit accout
=render 'users/form'

app/views/users/index.html.haml
%h1{align:"center"} All Users
.center
  =will_paginate
= @users.each do |user|
  %ul.listnig
    .row
      .well.col-md-4.offset-4
        %li= link_to user.name ,  user_path(user)
        %li
          %small=pluralize(user.articles.count, "article") if user.articles
        %li
          - if logged_in? and current_user.admin?
            = link_to "delete user", user_path(user), method: :delete, data: {confirm: "are you sure ?"}
.center
  =will_paginate

app/views/users/new.html.haml
%h1{align: "center"} Creater accout
=render 'users/form'

app/views/users/show.html.haml
%h1{align: "center"} Welcome to #{@user.name}
.container
  .row
    %h4 #{@user.name}'s articles
    .center
    =will_paginate @user_article
  = render 'articles/article', obj: @user.articles